source 'https://rubygems.org'

gem 'rails', '4.1.1'
gem 'rails-api'
gem 'jbuilder'
gem 'paperclip', '4.1'
gem 'fog', '~> 1.22.1'
gem 'inifile', '~> 2.0.2'
gem 'rest-client', '~> 1.6.7'
gem 'commander', '~> 4.2.0'
gem 'delayed_job_active_record'

group :development, :test do
  gem 'spring'
  gem 'rspec-rails'
  gem 'factory_girl_rails', '4.4.0'
  gem 'fakeweb'
  gem 'timecop'
  gem 'database_cleaner'
  gem 'map_by_method'
  gem 'what_methods'
end

gem 'pg'



# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.1.2'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
